source 'https://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'spyglass', path: '../spyglass'
gem 'thor'
gem 'log4r'
gem 'eventmachine'
gem 'em-websocket'
gem 'tomdoc'
gem 'yajl-ruby'
gem 'debugger'
gem 'text-table'
gem 'diff-lcs'
